# Site Settings
title: Design Informatics Lab | ASU
email: yiren@asu.edu
description: >
  Design Informatics Lab at ASU.
baseurl: ""
url: "http://designinformaticslab.github.io/"
github_username:  designinformaticslab
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
