# Site Settings
title: Yi Ren
email: yiren@asu.edu
description: >
  Yi Ren's research website
baseurl: ""
url: ""
github_username:  designinformaticslab
# Build Settings

include: []
exclude: []
kramdown:
  input: GFM
encoding: UTF-8

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

remote_theme: vaibhavvikas/jekyll-theme-minimalistic

